---
apiVersion: v1
kind: Secret
metadata: 
  name: bggdb-secret
  labels:
    name: bggdb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  ROOT_PASSWORD: cm9vdA==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata: 
  name: bggdb-cluster
  labels:
    name: bggdb-cluster
spec:
  replicas: 2
  secretName: bggdb-secret
  image: stackupiss/bgg-database:v1
  volumeSpec:
    persistentVolumeClaims:
      accessModes:
      - ReadWriteOnce
      storageClassName:
      do-block-storage
      resources:
        requests:
          storage: 1G