---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
     matchLabels:
        name: dov-pod
        version: v1
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        version: v1
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: dov-secret
        # - configMapRef:
        #     name: dov_cm
        #- name: INSTANCE_NAME
        #  value: dov
        #- name: HASH_NAME
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.podIP
        ports:
        - name: dov-port
          containerPort: 3000  
---
apiVersion: v1
kind: Service
metadata: 
 name: dov-svc
 labels:
    name: dov-svc
spec:
  type: LoadBalancer
  # type: NodePort
  # type: ClusterIP
  selector:
    name: dov-pod
    version: v1
  ports:
  - name: dov-svc-port
    port: 8080
    targetPort: dov-port