---
apiVersion: v1
kind: Pod
metadata:
   name: dov-pod
   labels:
    name: dov-pod
    app: dov
    tier: backend
  annotations:
    cost-center: abcd1234
spec:
    containers:
    - name: dov-containers
      image: stackupiss/dov-bear:v2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3000
      env:
      - name: INSTANCE_NAME
        value: dov-bear
      - name: HASH_NAME
        valueFrom:
          fieldRef:
          fieldPath: metadata.annotations['cost-center']