---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
     matchLabels:
        name: bggapp-pod
        version: v1
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        version: v1
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggapp-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
      livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          failureThreshold: 3
          periodSeconds: 30
           strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 25%
   maxUnavailable: 5%
---
apiVersion: v1
kind: Service
metadata: 
 name: bggapp-svc
 labels:
    name: bggapp-svc
spec:
  #normally used for internal
  type: LoadBalancer 
  selector:
    name: bggapp-pod
    version: v1
  ports:
  - name: bggapp-svc-port
    port: 80
    targetPort: bggapp-port